routes/web.php
<?php

// Site routes
Route::group(['as' => 'site.'], function () {
    // Start page
    Route::get('/', 'IndexController@index')->name('index');

    // Products routes
    Route::group([
        'prefix' => 'products',
        'as'     => 'products.',
    ], function () {
        Route::get('/', 'ProductController@index')
             ->name('index');
        Route::get('{product}', 'ProductController@show')
             ->name('show');
        Route::post('{product}/reviews', 'ReviewController@store')
             ->name('store_reviews');
    });

    // Categories routes
    Route::group([
        'prefix' => 'categories',
        'as'     => 'categories.',
    ], function () {
        Route::get('/', 'CategoryController@index')
             ->name('index');
        Route::get('{segments}', 'CategoryController@show')
             ->where('segments', '.*')->name('show');
    });
});


// Admin panel routes
Route::group([
    'prefix'     => 'admin',
    'namespace'  => 'Admin',
    'middleware' => 'auth',
    'as'         => 'admin.',
], function () {
    // Start page
    Route::get('/', 'IndexController@index')->name('index');

    // Products routes
    Route::resource('products', 'ProductController')
         ->except(['show']);

    // Reviews routes
    Route::resource('reviews', 'ReviewController')
         ->except(['show', 'create', 'store']);
    Route::get('reviews/{review}/change_status', 'ReviewController@changeStatus')
         ->name('reviews.change_status');

    // Categories routes
    Route::resource('categories', 'CategoryController');

    // Parser
    Route::resource('parse_items', 'ParserController');
});


// Export to excel
Route::get('export/products', 'ExportController@exportProducts')
     ->name('export.products');


Auth::routes();

// Redirect if route is register
Route::match(['get', 'post'], '/register', function () {
    return redirect()->route('site.index');
});

app/Http/Controllers/Admin/ReviewController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Review;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ReviewController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $reviews = Review::with(['user', 'product'])
                         ->latest()
                         ->paginate(20);

        return view('admin.reviews.index', compact('reviews'));
    }

    /**
     * @param \App\Review $review
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Review $review)
    {
        return view('admin.reviews.edit', compact('review'));
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Review              $review
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, Review $review)
    {
        $review->update($request->all());

        return redirect()->back()
                         ->with("success", "Review updated successfully!");
    }

    /**
     * @param \App\Review              $review
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function changeStatus(Review $review)
    {
        $review->update(['active' => $review->active === 1 ? 0 : 1]);

        return redirect()->back()
                         ->with("success", "Status changed!");
    }

    /**
     * @param \App\Review $review
     *
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy(Review $review)
    {
        $review->delete();

        return redirect()->route('admin.reviews.index')
                         ->with('success', 'Review deleted successfully!');
    }
}

app/Http/Controllers/ReviewController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\Review;
use Illuminate\Http\Request;
use Auth;

class ReviewController extends Controller
{

    /**
     * @param \Illuminate\Http\Request $request
     * @param                          $id
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request, $id)
    {
        $product = Product::find($id);

        if ($product) {
            $request->merge(['user_id' => Auth::id()]);

            $product->reviews()->create($request->all());

            return redirect()->back()->with('success', 'You review saved.');
        }

        return redirect()->back()->with('error', 'An error has occurred.');
    }
}

resources/views/admin/reviews/edit.blade.php
@extends('layouts.admin')

@section('title','Edit review')

@section('content')
    <div class="card">
        <div class="card-header">
            {{ link_to_route('admin.reviews.index', '<', null, ['class' => 'btn btn-secondary btn-sm mr-2']) }}
            Edit review
        </div>

        <div class="card-body">
            @if(session()->has('success'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{ session('success') }}

                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endif

            {!! Form::open()->method('patch')->route('admin.reviews.update', ['review' => $review])->fill($review) !!}
            {!! Form::text('name', 'Name')->required() !!}

            <rating value="{{ $review->rating }}"></rating>

            {!! Form::textarea('content', 'Text')->required() !!}

            @if($review->active === 1)
                {!! Form::radio('active', 'Active', 1)->attrs(['checked' => true]) !!}
                {!! Form::radio('active', 'Inactive', 0) !!}
            @elseif($review->active === 0)
                {!! Form::radio('active', 'Active', 1) !!}
                {!! Form::radio('active', 'Inactive', 0)->attrs(['checked' => true]) !!}
            @endif

            {!! Form::submit('Update review') !!}
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/admin/reviews/index.blade.php
@extends('layouts.admin')

@section('title', 'Reviews')

@section('content')
    <div class="card">
        <div class="card-header d-flex justify-content-between">
            Reviews
        </div>

        <div class="card-body">
            <table class="table table-striped table-bordered table-hover table-sm mb-4">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Product</th>
                    <th scope="col">User ID</th>
                    <th scope="col">Name</th>
                    <th scope="col">Rating</th>
                    <th scope="col">Text</th>
                    <th scope="col">Created</th>
                    <th scope="col">Status</th>
                    <th scope="col">Edit</th>
                </tr>
                </thead>
                <tbody class="small">
                @foreach($reviews as $review)
                    <tr>
                        <th scope="row" align="center">{{ $loop->iteration }}</th>
                        <td width="120">{{ link_to_route('site.products.show', $review->product->title, ['slug' => $review->product->slug]) }}</td>
                        <td align="center">{{ $review->user->id }}</td>
                        <td>{{ $review->name }}</td>
                        <td align="center">{{ $review->rating }}</td>
                        <td>{{ $review->content }}</td>
                        <td>{{ $review->created_at }}</td>
                        <td align="center">
                            <a href="{{ route('admin.reviews.change_status', ['review' => $review]) }}">
                                <i class="fas {{ $review->active ? 'fa-check-square' : 'fa-square' }}"></i>
                            </a>
                        </td>
                        <td align="center">
                            <div class="d-flex">
                                <a href="{{ route('admin.reviews.edit', ['review' => $review]) }}"
                                   class="mx-1">
                                    <i class="fas fa-pencil-alt"></i>
                                </a>

                                <a href="#" class="delete-link mx-1">
                                    <i class="far fa-trash-alt"></i>
                                </a>

                                {!! Form::open()->route('admin.reviews.destroy', ['review' => $review])
                                ->method('delete')
                                ->attrs(['style' => 'display: none;', 'class' => 'delete-form'])
                                 !!}
                                {!! Form::close() !!}
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>

            {{ $reviews->links() }}
        </div>
    </div>
@endsection