routes/web.php
<?php

// Site routes
Route::group(['as' => 'site.'], function () {
    // Start page
    Route::get('/', 'IndexController@index')->name('index');

    // Products routes
    Route::group([
        'prefix' => 'products',
        'as'     => 'products.',
    ], function () {
        Route::get('/', 'ProductController@index')
             ->name('index');
        Route::get('{product}', 'ProductController@show')
             ->name('show');
        Route::post('{product}/reviews', 'ReviewController@store')
             ->name('store_reviews');
    });

    // Categories routes
    Route::group([
        'prefix' => 'categories',
        'as'     => 'categories.',
    ], function () {
        Route::get('/', 'CategoryController@index')
             ->name('index');
        Route::get('{segments}', 'CategoryController@show')
             ->where('segments', '.*')->name('show');
    });
});


// Admin panel routes
Route::group([
    'prefix'     => 'admin',
    'namespace'  => 'Admin',
    'middleware' => 'auth',
    'as'         => 'admin.',
], function () {
    // Start page
    Route::get('/', 'IndexController@index')->name('index');

    // Products routes
    Route::resource('products', 'ProductController')
         ->except(['show']);

    // Reviews routes
    Route::resource('reviews', 'ReviewController')
         ->except(['show', 'create', 'store']);
    Route::get('reviews/{review}/change_status', 'ReviewController@changeStatus')
         ->name('reviews.change_status');

    // Categories routes
    Route::resource('categories', 'CategoryController');

    // Parser
    Route::resource('parse_items', 'ParserController');
});


// Export to excel
Route::get('export/products', 'ExportController@exportProducts')
     ->name('export.products');


Auth::routes();

// Redirect if route is register
Route::match(['get', 'post'], '/register', function () {
    return redirect()->route('site.index');
});

app/Http/Controllers/Admin/ParserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\ParseItemRequest;
use App\ParseItem;
use App\Services\ParserService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ParserController extends Controller
{

    public function index()
    {
        $parse_items = ParseItem::all();

        return view('admin.parser.index', compact('parse_items'));
    }

    public function show(ParseItem $parse_item)
    {
        $parser = new ParserService($parse_item->url);
        $items  = $parser->getPage()
                         ->getItems($parse_item->selector)
                         ->extractItems($parse_item->fields_array);

        return view('admin.parser.show', compact('parse_item', 'items'));
    }

    public function create()
    {
        return view('admin.parser.create');
    }

    public function store(ParseItemRequest $request)
    {
        $request->merge(['fields' => json_encode($request->fields)]);

        ParseItem::create($request->all());

        return view('admin.parser.create');
    }

    public function edit(ParseItem $parse_item)
    {
        return view('admin.parser.edit', compact('parse_item'));
    }

    public function update(ParseItemRequest $request, ParseItem $parse_item)
    {
        $request->merge(['fields' => json_encode($request->fields)]);

        $parse_item->update($request->all());

        return redirect()->back()->with('success', 'Resource updated successfully!');
    }

    public function destroy(ParseItem $parse_item)
    {
        $parse_item->delete();

        return redirect()->back()->with('success', 'Resource deleted successfully!');
    }
}

resources/views/admin/parser/create.blade.php
@extends('layouts.admin')

@section('title', 'Parser')

@section('content')
    <div class="card">
        <div class="card-header">
            {{ link_to_route('admin.parse_items.index', '<', null, ['class' => 'btn btn-secondary btn-sm mr-2']) }}
            New parser resource
        </div>

        <div class="card-body">
            {!! Form::open()->method('post')->route('admin.parse_items.store') !!}
            {!! Form::text('title', 'Title *')->placeholder('Enter title')->required() !!}
            {!! Form::text('type', 'Type (example: products or categories)*')->placeholder('Enter type')->required() !!}
            {!! Form::text('url', 'Resource URL *')->placeholder('Enter resource url')->required() !!}
            {!! Form::text('selector', 'Item selector *')->placeholder('Enter item selector')->required() !!}

            <div class="fields-label">Fields</div>
            <div class="fields-group mb-3">
                <div class="fields-add d-flex justify-content-between align-items-center">
                    <span>Title: <input type="text" class="field-title-input small"></span>
                    <span>Value: <input type="text" class="field-value-input small"></span>
                    <button class="btn btn-sm field-add-button">Add new field</button>
                </div>

                <ul class="fields-list list-group mt-2">
                    @if(old('fields'))
                        @foreach(old('fields') as $title => $value)
                            <li class="list-group-item p-1 d-flex justify-content-between align-items-center">
                                <span>{{ $title }}: {{ $value }}</span>
                                <span class="badge badge-secondary badge-pill delete-field" style="cursor: pointer;">Delete</span>
                                <input type="hidden" name="fields[{{ $title }}]" value="{{ $value }}">
                            </li>
                        @endforeach
                    @endif
                </ul>
            </div>

            {!! Form::submit('Save resource') !!}
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/admin/parser/edit.blade.php
@extends('layouts.admin')

@section('title', 'Parser')

@section('content')
    <div class="card">
        <div class="card-header">
            {{ link_to_route('admin.parse_items.index', '<', null, ['class' => 'btn btn-secondary btn-sm mr-2']) }}
            New parser resource
        </div>

        <div class="card-body">
            @if(session()->has('success'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{ session('success') }}

                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endif

            {!! Form::open()->method('patch')->route('admin.parse_items.update', ['parse_item' => $parse_item])->fill($parse_item) !!}
            {!! Form::text('title', 'Title *')->placeholder('Enter title')->required() !!}
            {!! Form::text('type', 'Type (example: products or categories)*')->placeholder('Enter type')->required() !!}
            {!! Form::text('url', 'Resource URL *')->placeholder('Enter resource url')->required() !!}
            {!! Form::text('selector', 'Item selector *')->placeholder('Enter item selector')->required() !!}

            <div class="fields-label">Fields</div>
            <div class="fields-group mb-3">
                <div class="fields-add d-flex justify-content-between align-items-center">
                    <span>Title: <input type="text" class="field-title-input small"></span>
                    <span>Value: <input type="text" class="field-value-input small"></span>
                    <button class="btn btn-sm field-add-button">Add new field</button>
                </div>

                <ul class="fields-list list-group mt-2">
                    @if(old('fields'))
                        @foreach(old('fields') as $title => $value)
                            <li class="list-group-item p-1 d-flex justify-content-between align-items-center">
                                <span>{{ $title }}: {{ $value }}</span>
                                <span class="badge badge-secondary badge-pill delete-field" style="cursor: pointer;">Delete</span>
                                <input type="hidden" name="fields[{{ $title }}]" value="{{ $value }}">
                            </li>
                        @endforeach
                    @endif

                    @if($parse_item->fields)
                        @foreach(json_decode($parse_item->fields, true) as $title => $value)
                            <li class="list-group-item p-1 d-flex justify-content-between align-items-center">
                                <span>{{ $title }}: {{ $value }}</span>
                                <span class="badge badge-secondary badge-pill delete-field" style="cursor: pointer;">Delete</span>
                                <input type="hidden" name="fields[{{ $title }}]" value="{{ $value }}">
                            </li>
                        @endforeach
                    @endif
                </ul>
            </div>

            {!! Form::submit('Save resource') !!}
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/admin/parser/index.blade.php
@extends('layouts.admin')

@section('title', 'Parser')

@section('content')
    <div class="card">
        <div class="card-header d-flex justify-content-between">
            Parse resources

            {{ link_to_route('admin.parse_items.create', 'Add new resource') }}
        </div>

        <div class="card-body">
            @if(session()->has('success'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{ session('success') }}

                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endif

            <ul class="list-group">
                @forelse($parse_items as $item)
                    <li class="list-group-item">
                        <div><b>{{ $item->title }}</b></div>
                        <div class="small"><b>Type: </b><i>{{ $item->type }}</i></div>
                        <div class="small"><b>URL: </b><i>{{ $item->url }}</i></div>
                        <div class="small"><b>Item selector: </b><i>"{{ $item->selector }}"</i></div>
                        <div class="small"><b>Fields: </b>
                            @foreach($item->fields_array as $title => $selector)
                                <div>{{ $title }} => <i>"{{ $selector }}"</i></div>
                            @endforeach
                        </div>
                        <div class="d-flex justify-content-between">
                            <a href="{{ route('admin.parse_items.show', ['parse_item' => $item]) }}">Parse</a>

                            <div>
                                <a href="{{ route('admin.parse_items.edit', ['parse_item' => $item]) }}">Edit</a>

                                <a href="#" class="delete-link">Delete</a>

                                {!! Form::open()->route('admin.parse_items.destroy', ['parse_item' => $item])
                                ->method('delete')
                                ->attrs(['style' => 'display: none;', 'class' => 'delete-form'])
                                 !!}
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </li>
                @empty
                    <p>No resources</p>
                @endforelse
            </ul>
        </div>
    </div>
@endsection

resources/views/admin/parser/show.blade.php
@extends('layouts.admin')

@section('title', 'Parser')

@section('content')
    <div class="card">
        <div class="card-header">Parse source "{{ $parse_item->title }}"</div>

        <div class="card-body">
            <ul class="list-group">
                @foreach($items as $item)
                    <li class="list-group-item">
                        @foreach($item as $key => $value)
                            <div><b>{{ $key }}: </b><i>{{ $value }}</i></div>
                        @endforeach

                        {{ link_to_route('admin.' . $parse_item->type . '.create', 'Add to ' . $parse_item->type, $item) }}
                    </li>
                @endforeach
            </ul>
        </div>
    </div>
@endsection