routes/web.php
<?php

// Site routes
Route::group(['as' => 'site.'], function () {
    // Start page
    Route::get('/', 'IndexController@index')->name('index');

    // Products routes
    Route::group([
        'prefix' => 'products',
        'as'     => 'products.',
    ], function () {
        Route::get('/', 'ProductController@index')
             ->name('index');
        Route::get('{product}', 'ProductController@show')
             ->name('show');
        Route::post('{product}/reviews', 'ReviewController@store')
             ->name('store_reviews');
    });

    // Categories routes
    Route::group([
        'prefix' => 'categories',
        'as'     => 'categories.',
    ], function () {
        Route::get('/', 'CategoryController@index')
             ->name('index');
        Route::get('{segments}', 'CategoryController@show')
             ->where('segments', '.*')->name('show');
    });
});


// Admin panel routes
Route::group([
    'prefix'     => 'admin',
    'namespace'  => 'Admin',
    'middleware' => 'auth',
    'as'         => 'admin.',
], function () {
    // Start page
    Route::get('/', 'IndexController@index')->name('index');

    // Products routes
    Route::resource('products', 'ProductController')
         ->except(['show']);

    // Reviews routes
    Route::resource('reviews', 'ReviewController')
         ->except(['show', 'create', 'store']);
    Route::get('reviews/{review}/change_status', 'ReviewController@changeStatus')
         ->name('reviews.change_status');

    // Categories routes
    Route::resource('categories', 'CategoryController');

    // Parser
    Route::resource('parse_items', 'ParserController');
});


// Export to excel
Route::get('export/products', 'ExportController@exportProducts')
     ->name('export.products');


Auth::routes();

// Redirect if route is register
Route::match(['get', 'post'], '/register', function () {
    return redirect()->route('site.index');
});

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Admin Panel | @yield('title')</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="{{ asset('js/admin.js') }}" defer></script>
    {{--<script src="{{ asset('js/filter.js') }}" defer></script>--}}
    <script>
      window.Laravel = {!! json_encode([
            'csrfToken' => csrf_token(),
            'baseUrl' => URL::to('/')
        ]) !!}
    </script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">

    <!-- Icons -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
        <div class="container">
            <a class="navbar-brand" href="{{ route('admin.index') }}">
                Admin Panel
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        {{ link_to_route('admin.products.index', 'Products', null, ['class' => 'nav-link']) }}
                    </li>

                    <li class="nav-item">
                        {{ link_to_route('admin.categories.index', 'Categories', null, ['class' => 'nav-link']) }}
                    </li>

                    <li class="nav-item">
                        {{ link_to_route('admin.reviews.index', 'Reviews', null, ['class' => 'nav-link']) }}
                    </li>

                    <li class="nav-item">
                        {{ link_to_route('admin.parse_items.index', 'Parser', null, ['class' => 'nav-link']) }}
                    </li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    @auth
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                Admin
                                <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('site.index') }}">Go to site</a>

                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                      style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endauth
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-lg-10">
                    @yield('content')
                </div>
            </div>
        </div>
    </main>
</div>
</body>
</html>

resources/views/layouts/site.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name') }} | @yield('title')</title>
    <meta name="description" content="@yield('description')">
    <meta name="keywords" content="@yield('keywords')">

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    {{--<script src="{{ asset('js/filter.js') }}" defer></script>--}}
    <script>
      window.Laravel = {!! json_encode([
            'csrfToken' => csrf_token(),
            'baseUrl' => URL::to('/')
        ]) !!}
    </script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">

    <!-- Icons -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name') }}
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        {{ link_to_route('site.products.index', 'All products', null, ['class' => 'nav-link']) }}
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="categoryMenu" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Categories
                        </a>
                        <div class="dropdown-menu" aria-labelledby="categoryMenu">
                            <a href="{{ route('site.categories.index') }}" class="dropdown-item">
                                All categories
                            </a>

                            <div class="dropdown-divider"></div>

                            @foreach($nav_categories as $category)
                                <a href="{{ route('site.categories.show', ['segments' => $category->urlSegments()]) }}"
                                   class="dropdown-item">
                                    {{ $category->title }}
                                </a>
                            @endforeach
                        </div>
                    </li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    @auth
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                Admin
                                <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('admin.index') }}">Admin panel</a>

                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                      style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endauth
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <nav class="col-6 col-md-4 col-lg-3">
                    <div class="border p-2">
                        <h5 class="text-center py-3">Categories</h5>

                        @include('components.menu', ['categories' => $nav_categories])
                    </div>
                </nav>

                <div class="col-6 col-md-8 col-lg-9">
                    @yield('content')
                </div>
            </div>
        </div>
    </main>
</div>
</body>
</html>