routes/web.php
<?php

// Site routes
Route::group(['as' => 'site.'], function () {
    // Start page
    Route::get('/', 'IndexController@index')->name('index');

    // Products routes
    Route::group([
        'prefix' => 'products',
        'as'     => 'products.',
    ], function () {
        Route::get('/', 'ProductController@index')
             ->name('index');
        Route::get('{product}', 'ProductController@show')
             ->name('show');
        Route::post('{product}/reviews', 'ReviewController@store')
             ->name('store_reviews');
    });

    // Categories routes
    Route::group([
        'prefix' => 'categories',
        'as'     => 'categories.',
    ], function () {
        Route::get('/', 'CategoryController@index')
             ->name('index');
        Route::get('{segments}', 'CategoryController@show')
             ->where('segments', '.*')->name('show');
    });
});


// Admin panel routes
Route::group([
    'prefix'     => 'admin',
    'namespace'  => 'Admin',
    'middleware' => 'auth',
    'as'         => 'admin.',
], function () {
    // Start page
    Route::get('/', 'IndexController@index')->name('index');

    // Products routes
    Route::resource('products', 'ProductController')
         ->except(['show']);

    // Reviews routes
    Route::resource('reviews', 'ReviewController')
         ->except(['show', 'create', 'store']);
    Route::get('reviews/{review}/change_status', 'ReviewController@changeStatus')
         ->name('reviews.change_status');

    // Categories routes
    Route::resource('categories', 'CategoryController');

    // Parser
    Route::resource('parse_items', 'ParserController');
});


// Export to excel
Route::get('export/products', 'ExportController@exportProducts')
     ->name('export.products');


Auth::routes();

// Redirect if route is register
Route::match(['get', 'post'], '/register', function () {
    return redirect()->route('site.index');
});

app/Category.php
<?php

namespace App;

use App\Services\ImageService;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['parent_id', 'slug', 'title', 'image'];
    protected $appends = ['image_src'];
    protected $with = ['parent'];

    // Products in current category
    public function products()
    {
        return $this->belongsToMany(Product::class);
    }


    // Parent category of current
    public function parent()
    {
        return $this->belongsTo(Category::class, 'parent_id');
    }


    // Children categories of current
    public function children()
    {
        return $this->hasMany(Category::class, 'parent_id');
    }

    // Segments string of slugs ('slug-parent/slug-child/slug-child2/...')
    public function urlSegments()
    {
        $segments = '';

        if($this->parent) {
            $segments .= $this->parent->urlSegments() . '/' ;
        }

        return $segments . $this->slug;
    }

    // Scope isParent
    public function scopeIsParent($query)
    {
        return $query->whereNull('parent_id');
    }

    public function getImageSrcAttribute()
    {
        return ImageService::getImageSrc($this->image, 'products');
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Http\Requests\CategoryRequest;
use App\Services\ImageService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{

    /**
     * Show all categories
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $categories = Category::with('children')->whereNull('parent_id')->get();

        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show category with subcategories
     *
     * @param \App\Category $category
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\RedirectResponse|\Illuminate\View\View
     */
    public function show(Category $category)
    {
        if ($category->parent_id) {
            return redirect()->back();
        }

        return view('admin.categories.show',
            ['category' => $category->load('children')]);
    }

    /**
     * Create page
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function create(Request $request)
    {
        if ($request->parent) {
            $category = Category::find($request->parent);

            if (!$category || $category->parent) {
                return redirect()->route('admin.categories.index');
            }

            return view('admin.categories.create', compact('category'));
        }

        return view('admin.categories.create');
    }

    /**
     * Save category
     *
     * @param \App\Http\Requests\CategoryRequest $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CategoryRequest $request)
    {
        // If request has a file
        if ($request->hasFile('file')) {
            $image = $request->file('file');

            // Create an image name
            $image_name = ImageService::createImageName($image, 'category');

            // Store the file
            ImageService::storeImage(
                $image,
                $image_name,
                400,
                300,
                'categories'
            );
        }

        // Add a field to the request array
        $request->request->add(['image' => $image_name ?? null]);

        // Store the category
        Category::create($request->all());

        if ($request->has('parent_id')) {
            // Redirect to category page
            return redirect()->route('admin.categories.show',
                ['category' => $request->parent_id])
                             ->with("success", "Subcategory created successfully!");
        } else {
            // Redirect to categories page
            return redirect()->route('admin.categories.index')
                             ->with("success", "Category created successfully!");
        }
    }

    /**
     * Edit page
     *
     * @param \App\Category $category
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Category $category)
    {
        return view('admin.categories.edit', compact('category'));
    }

    /**
     * Update category
     *
     * @param \App\Http\Requests\CategoryRequest $request
     * @param \App\Category                      $category
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(CategoryRequest $request, Category $category)
    {
        // If request has a file
        if ($request->hasFile('file')) {
            $image = $request->file('file');

            // Create an image name
            $image_name = ImageService::createImageName($image, 'category');

            // Store the file
            ImageService::storeImage(
                $image,
                $image_name,
                400,
                300,
                'categories'
            );
        }

        // Add a field to the request array
        $request->request->add(['image' => $image_name ?? $category->image ?? null]);

        // Store the category
        $category->update($request->all());

        // Redirect to products page
        return redirect()->back()
                         ->with("success", "Category updated successfully!");

    }

    /**
     * Delete category
     *
     * @param \App\Category $category
     *
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy(Category $category)
    {
        $parent_id = $category->parent_id;

        $category->delete();

        if ($parent_id) {
            return redirect()->route('admin.categories.show',
                ['category' => $parent_id])
                             ->with('success', 'Subcategory deleted successfully!');
        } else {
            return redirect()->route('admin.categories.index')
                             ->with('success', 'Category deleted successfully!');

        }
    }

}

app/Http/Controllers/Api/v1/CategoryController.php
<?php

namespace App\Http\Controllers\Api\v1;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{


    /**
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Request $request)
    {
        $category = null;

        // Get uri segments after
        $uri_segments = explode('/', $request->segments);

        foreach ($uri_segments as $key => $value) {
            if ($key === 0) {
                // Get parent category
                $category = Category::isParent()->whereSlug($value)->with([
                    'children' => function ($query) {
                        $query->withCount('products');
                        $query->withCount('children');
                    },
                ])->first();
            } else {
                // Get subcategory
                $subcategory = $category->children()->whereSlug($value)->with([
                    'children' => function ($query) {
                        $query->withCount('products');
                        $query->withCount('children');
                    },
                ])->first();

                $category = $subcategory;
            }
        }

        $products = $category->products()
                             ->filter()
                             ->latest()
                             ->paginate(6)
                             ->appends($request->all());

        return response()->json($products);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $categories = Category::whereNull('parent_id')
                              ->withCount('children')
                              ->get();

        return view('site.categories.index', compact('categories'));
    }

    /**
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Request $request)
    {
        $category = null;

        // Get uri segments after
        $uri_segments = explode('/', $request->segments);

        foreach ($uri_segments as $key => $value) {
            if ($key === 0) {
                // Get parent category
                $category = Category::isParent()->whereSlug($value)->with([
                    'children' => function ($query) {
                        $query->withCount('products');
                        $query->withCount('children');
                    },
                ])->first();
            } else {
                // Get subcategory
                $subcategory = $category->children()->whereSlug($value)->with([
                    'children' => function ($query) {
                        $query->withCount('products');
                        $query->withCount('children');
                    },
                ])->first();

                // If subcategory not found and segment is latest
                if ( ! $subcategory && (count($uri_segments) == $key + 1)) {
                    // Get product
                    $product = $category->products()->whereSlug($value)->first();

                    // Show product if found
                    if ($product) {
                        return view('site.products.show',
                            compact('product'));
                    }
                }

                $category = $subcategory;
            }

            // If category not found
            if ( ! $category) {
                return view('site.categories.not_found',
                    ['category_name' => $value]);
            }
        }

        return view('site.categories.show', compact('category'));
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.admin')

@section('title','Add new ' . (isset($category) ? 'subcategory' : 'category'))

@section('content')
    <div class="card">
        <div class="card-header">
            @if(isset($category))
                {{ link_to_route('admin.categories.show', '<', ['category' => $category], ['class' => 'btn btn-secondary btn-sm mr-2']) }}
                Add new subcategory
            @else
                {{ link_to_route('admin.categories.index', '<', null, ['class' => 'btn btn-secondary btn-sm mr-2']) }}
                Add new category
            @endif
        </div>

        <div class="card-body">
            {!! Form::open()->route('admin.categories.store')->multipart() !!}

            @if(isset($category))
                {!! Form::hidden('parent_id')->value($category->id) !!}
            @endif

            {!! Form::text('title', 'Title *')->placeholder('Enter title')->required() !!}
            {!! Form::text('slug', 'Url slug (example: my-first-category) *')->placeholder('Enter url slug')->required() !!}
            {!! Form::file('file', 'Add image')->required(false) !!}
            {!! Form::submit('Save category') !!}
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin')

@section('title','Edit ' . ($category->parent_id ? 'subcategory' : 'category'))

@section('content')
    <div class="card">
        <div class="card-header">
            @if($category->parent_id)
                {{ link_to_route('admin.categories.show', '<', ['category' => $category->parent_id], ['class' => 'btn btn-secondary btn-sm mr-2']) }}
                Edit subcategory - {{ $category->title }}
            @else
                {{ link_to_route('admin.categories.index', '<', null, ['class' => 'btn btn-secondary btn-sm mr-2']) }}
                Edit category - {{ $category->title }}
            @endif
        </div>

        <div class="card-body">
            @if(session()->has('success'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{ session('success') }}

                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endif

            {!! Form::open()->route('admin.categories.update', ['category' => $category])->fill($category)->method('patch')->multipart() !!}

            @if($category->parent_id)
                {!! Form::hidden('parent_id') !!}
            @endif

            {!! Form::text('title', 'Title *')->placeholder('Enter title')->required() !!}
            {!! Form::text('slug', 'Url slug (example: my-first-category) *')->placeholder('Enter url slug')->required() !!}

            <div class="d-flex justify-content-center">
                <img class="card-img-top img-thumbnail" src="{{ $category->image_src }}" alt="{{ $category->title }}"
                     style="display: block;max-width: 300px;width: 100%;height: auto;">
            </div>

            {!! Form::file('file', $category->image ? 'Change image' : 'Add image')->required(false) !!}
            {!! Form::submit('Update category') !!}
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.admin')

@section('title', 'Categories')

@section('content')
    <div class="card">
        <div class="card-header d-flex justify-content-between">
            <span>Categories</span>

            {{ link_to_route('admin.categories.create', 'Add category', null, ['class' => 'btn btn-secondary btn-sm']) }}
        </div>

        <div class="card-body">
            @if(session()->has('success'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{ session('success') }}

                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endif

            @if($categories->count())
                <table class="table table-striped table-bordered table-hover table-sm mb-4">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Image</th>
                        <th scope="col">Title</th>
                        <th scope="col">Subcategories</th>
                        <th scope="col">Created</th>
                        <th scope="col">Edit</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($categories as $category)
                        <tr>
                            <th scope="row">{{ $loop->iteration }}</th>
                            <td>
                                <img src="{{ $category->image_src }}" alt="{{ $category->title }}" style="width: 80px">
                            </td>
                            <td>{{ link_to_route('admin.categories.show', $category->title, ['category' => $category]) }}</td>
                            <td>
                                @foreach($category->children as $subcategory)
                                    <span class="d-block border border-secondary rounded ml-1 mb-1 px-1 small">
                                    {{ $subcategory->title }}
                                </span>
                                @endforeach
                            </td>
                            <td class="small">{{ $category->created_at }}</td>
                            <td>
                                <a href="{{ route('admin.categories.edit', ['category' => $category]) }}"
                                   class="mr-1 small">
                                    <i class="fas fa-pencil-alt"></i>
                                </a>

                                <a href="#" class="small delete-link">
                                    <i class="far fa-trash-alt"></i>
                                </a>

                                {!! Form::open()->route('admin.categories.destroy', ['category' => $category])
                                ->method('delete')
                                ->attrs(['style' => 'display: none;', 'class' => 'delete-form'])
                                 !!}
                                {!! Form::close() !!}
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            @else
                <p>No categories</p>
            @endif
        </div>
    </div>
@endsection

resources/views/admin/categories/show.blade.php
@extends('layouts.admin')

@section('title', 'Category - ' . $category->title)

@section('content')
    <div class="card">
        <div class="card-header d-flex justify-content-between">
            <span>
                {{ link_to_route('admin.categories.index', '<', null, ['class' => 'btn btn-secondary btn-sm mr-2']) }}

                Category - {{ $category->title }}
            </span>

            {{ link_to_route('admin.categories.create', 'Add subcategory', ['parent' => $category->id], ['class' => 'btn btn-secondary btn-sm']) }}
        </div>

        <div class="card-body">
            @if(session()->has('success'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{ session('success') }}

                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endif

            @if($category->children->count())
                <p>Subcategories:</p>
                <table class="table table-striped table-bordered table-hover table-sm mb-4">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Image</th>
                        <th scope="col">Title</th>
                        <th scope="col">Created</th>
                        <th scope="col">Edit</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($category->children as $subcategory)
                        <tr>
                            <th scope="row">{{ $loop->iteration }}</th>
                            <td>
                                <img src="{{ $subcategory->image_src }}" alt="{{ $subcategory->title }}" style="width: 80px">
                            </td>
                            <td>{{ $subcategory->title }}</td>
                            <td class="small">{{ $subcategory->created_at }}</td>
                            <td>
                                <a href="{{ route('admin.categories.edit', ['category' => $subcategory]) }}"
                                   class="mr-1 small">
                                    <i class="fas fa-pencil-alt"></i>
                                </a>

                                <a href="#" class="small delete-link">
                                    <i class="far fa-trash-alt"></i>
                                </a>

                                {!! Form::open()->route('admin.categories.destroy', ['category' => $subcategory])
                                ->method('delete')
                                ->attrs(['style' => 'display: none;', 'class' => 'delete-form'])
                                 !!}
                                {!! Form::close() !!}
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            @else
                <p>No subcategories</p>
            @endif
        </div>
    </div>
@endsection